### ISSUE TITLE
Transition speed

### ISSUE THREAD

**Issue by macleod-ee** [1j01/pipes#1]
The current iteration is a lot faster than the original, any reason you opted for that?

**Comment by Qix-** [comment]
Further, it doesn't appear the option in the source for speed changes anything.

**Comment by 1j01** [comment]
@macleodsawyer Yeah, I tuned the speed for ease of development and never slowed it down to match the original (or for presentational aesthetics, because it really probably should be slower).
@Qix- Yep, that option is apparently unused and it's just hard-coded. `options.joints` definitely isn't respected either.

**Comment by Qix-** [comment]
Though teapot is, and that... is okay with me. :+1:

**Comment by 1j01** [comment]
I don't know what the exact range of the interval is, I looked at https://www.youtube.com/watch?v=XPZb8HoQgH8 and measured 18s and 22s, so I went with 16s to 24s (assuming it didn't hit the exact bounds of the range by random chance).
